PREFIX SRCNet: <http://example.org/SRCNet>
PREFIX SRC: <http://example.org/SRC>
PREFIX schema: <http://schema.org/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?SRC_name ?NumOfcpus
WHERE {
  ?node a SRC: .
  ?node schema:name ?SRC_name .
  
  ?node schema:hasComputing ?Computing .
  ?Computing schema:hasCPU ?CPU.
  ?CPU schema:numberOfCPUs ?NumOfcpus.
}
ORDER BY DESC(?NumOfcpus) 
LIMIT 1                  
