PREFIX src: <https://w3id.org/srcnet#>
PREFIX schema: <https://schema.org/>

SELECT ?srcName ?contactPointName # ?telephone ?email ?fax
## remove # in case you also need the contact details for the contact point.
WHERE {

  ?src a src:SRC ;
       schema:name ?srcName ;
       src:operatedBy ?org .

  ?org schema:contactPoint ?cp .

  ?cp schema:name ?contactPointName ;
    # schema:telephone ?telephone ;
    # schema:email ?email ;
    # schema:faxNumber ?fax .

  FILTER(?srcName = "canSRC")
}