PREFIX src: <https://w3id.org/srcnet#>
PREFIX schema: <https://schema.org/>
PREFIX dcterms: <http://purl.org/dc/terms/>

SELECT ?srcName ?nodeName ?countryName ?regionName ?externalBandwidth ?unit
WHERE {

  ?src a src:SRC ;
       schema:name ?srcName ;
       dcterms:hasPart ?node .

  OPTIONAL { ?node schema:name ?nodeName }

  ?node src:hasNetworkResource ?network .
  ?network src:hasBandwidth ?bandwidth .
  ?bandwidth src:externalBandwidth ?external .

  ?external schema:value ?externalBandwidth ;
            schema:unitCode ?unit .
  {
      ?src src:operatedBy ?org .
  }
  UNION
  {
      ?node src:operatedBy ?org .
  }

  ?org schema:location ?place .
  ?place schema:address ?address .
  ?address schema:addressCountry ?country .
  ?country schema:name ?countryName ;
           schema:containedInPlace ?region .

  ?region schema:name ?regionName .

  FILTER(?regionName = "European Union" || ?regionName = "Europe")
}