PREFIX src: <https://w3id.org/srcnet#>
PREFIX dcat: <http://www.w3.org/ns/dcat#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX schema: <https://schema.org/>

SELECT ?srcName ?serviceName ?serviceId ?serviceVersion ?description
WHERE {

  ?src a src:SRC ;
       schema:name ?srcName ;
       dcterms:hasPart ?node .

  ?node src:localServiceCatalog ?catalog .

  ?catalog dcat:service ?service .

  ?service schema:name ?serviceName ;
           src:serviceId ?serviceId ;
           src:serviceVersion ?serviceVersion ;
           schema:description ?description .

  FILTER(?srcName = "espSRC")
}
ORDER BY ?serviceName