PREFIX src: <https://w3id.org/srcnet#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX dcat: <http://www.w3.org/ns/dcat#>
PREFIX schema: <https://schema.org/>

SELECT ?srcName ?serviceName ?memorySize ?unit
WHERE {
  ?src a src:SRC ;
       schema:name ?srcName ;
       dcterms:hasPart ?node .
  ?node src:localServiceCatalog ?catalog .
  ?catalog dcat:service ?service .
  
  ?service schema:name ?serviceName ;
           src:hasJupyterNotebook ?notebook ;
           src:resourceRequirements ?req .

  ?req src:memoryCapacity ?memory .
  ?memory schema:value ?memorySize ;
          schema:unitCode ?unit .

  FILTER(?memorySize > 32)
}
ORDER BY DESC(?memorySize)