PREFIX src: <https://w3id.org/srcnet#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX schema: <https://schema.org/>

SELECT ?srcName ?cores ?diskCapacity
WHERE {

  ?src a src:SRC ;
       schema:name ?srcName ;
       dcterms:hasPart ?node .

  ?node src:hasComputeResource ?compute .
  ?compute src:hasProcessor ?processor ;
           src:hasDisk ?disk .

  ?processor src:coreCount ?cores .
  ?disk src:diskCapacity ?diskValue .
  ?diskValue schema:value ?diskCapacity .

  FILTER(?cores >= 200 && ?diskCapacity >= 40)

}