PREFIX src: <https://w3id.org/srcnet#>
PREFIX dcat: <http://www.w3.org/ns/dcat#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX schema: <https://schema.org/>

SELECT ?srcName ?datasetId ?localPath
WHERE {

  ?src a src:SRC ;
       schema:name ?srcName ;
       dcterms:hasPart ?node .

  ?node src:localServiceCatalog ?catalog .

  ?catalog dcat:service ?service .

  ?service dcat:dataset ?dataset .

  ?dataset dcterms:title "wallaby-center.fits" ;
           dcterms:identifier ?datasetId ;
           src:localPath ?localPath .
}