PREFIX src: <https://w3id.org/srcnet#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX schema: <https://schema.org/>

SELECT ?srcName (COUNT(?node) AS ?numberOfNodes)
WHERE {

  ?src a src:SRC ;
       schema:name ?srcName ;
       dcterms:hasPart ?node .

  ?node a src:Node .

}
GROUP BY ?srcName
HAVING (COUNT(?node) > 1)