PREFIX src: <https://w3id.org/srcnet#>
PREFIX dcat: <http://www.w3.org/ns/dcat#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX schema: <https://schema.org/>

SELECT DISTINCT ?SRCname ?File ?localPath
WHERE {
 
  ?node a src:RegionalNode ;
          schema:name ?SRCname ;
          src:operatedBy ?org .
  
  ?org src:localServiceCatalog ?catalog .
  ?catalog dcat:service ?service .
  ?service schema:name ?serviceName ;
           dcat:dataset ?dataset .
  
  FILTER(LCASE(?serviceName) = "datalake")
  
  ?dataset dcterms:title ?title ;
           dcterms:identifier ?File ;
           src:localPath ?localPath .

FILTER(LCASE(?title) = "wallaby-center.fits")
}
