PREFIX src: <https://w3id.org/srcnet#>
PREFIX schema: <https://schema.org/>
PREFIX dcterms: <http://purl.org/dc/terms/>

SELECT ?srcName ?diskType
WHERE {

  ?src a src:SRC ;
       schema:name ?srcName ;
       dcterms:hasPart ?node .

  ?node src:hasComputeResource ?compute .
  ?compute src:hasDisk ?disk .
  ?disk schema:additionalType ?diskType .

  FILTER(?srcName = "espSRC")
}