PREFIX src: <https://w3id.org/srcnet#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX schema: <https://schema.org/>

SELECT ?srcName (SUM(?cores) AS ?totalCores)
WHERE {
  
  ?src a src:SRC ;
       schema:name ?srcName ;
       dcterms:hasPart ?node .

  ?node src:hasComputeResource ?compute .
  ?compute src:hasProcessor ?processor .
  ?processor src:coreCount ?cores .
}
GROUP BY ?srcName
ORDER BY DESC(?totalCores)
LIMIT 1