PREFIX src: <https://w3id.org/srcnet#>
PREFIX dcat: <http://www.w3.org/ns/dcat#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX schema: <https://schema.org/>

SELECT ?srcName ?toolName ?datasetTitle
WHERE {

  ?src a src:SRC ;
       schema:name ?srcName ;
       dcterms:hasPart ?node .

  ?node src:localServiceCatalog ?catalog .

  ?catalog dcat:service ?visualService .
  ?visualService src:hasVisualizationTool ?tool .
  ?tool schema:name ?toolName .

  ?catalog dcat:service ?dataService .
  ?dataService dcat:dataset ?dataset .
  
  ?dataset dcterms:title ?datasetTitle .

  FILTER(?datasetTitle = "wallaby-center.fits")
}